### PR TITLE
Simplified IPv6 setup documentation

### PR DESCRIPTION
**Pull request by louis89**

### CODE REVIEW

**Comment by aus** [comment]
Thank you for the PR! Coincidently, I've been playing with my IPv6 setup and managed to break the routing somehow (unrelated to your PR). 

I attempted your instructions, but I cannot get an IPv6 assignment. Playing with the GUI, it seems there can be some residual _Advanced Settings_ parameters that can carry over in the DHCP6 conf files even when Advanced Settings are disabled. Can you share your `/var/etc/dhcp6c_wan.conf`?

**Comment by aus** [comment]
For some reason, this config (similar to my original) will pull a IPv6:

```plain
interface ngeth0 {
        send ia-na 1;   # request stateful address
        send ia-pd 1;   # request prefix delegation - LAN
        request domain-name-servers;
        script "/var/etc/dhcp6c_wan_dhcp6withoutra_script.sh"; # we'd like nameservers and RTSOLD to do all the work
};
id-assoc na 1 { };
id-assoc pd 1 {
        prefix ::/60 infinity;
        prefix-interface bce1 {
                sla-id 0;
                sla-len 4;
        };
};
```

But the one generated via your instructions will not:

```plain
interface ngeth0 {
	send ia-na 0;	# request stateful address
	send ia-pd 0;	# request prefix delegation
	request domain-name-servers;
	request domain-name;
	script "/var/etc/dhcp6c_wan_dhcp6withoutra_script.sh"; # we'd like nameservers and RTSOLD to do all the work
};
id-assoc na 0 { };
id-assoc pd 0 {
	prefix ::/60 infinity;
	prefix-interface bce1 {
		sla-id 1;
		sla-len 4;
	};
};
```

The key difference being the Identify Association ID

**Comment by louis89** [comment]
Well that is odd... 

I agree that the identity association ID is the only important difference `1` in your config, `0` in mine, I'm not sure why that would make a difference. The only quirk I noted is that no site-level	aggregator ID should match the identity association ID, in this case I would inconsistently be assigned my IPv6 prefixes. Previously I was using Comcast and that quirk did not exist.

I can tell you I have been running this config for about two months now without any issues. It survives reboots, unplugging/replugging router gateway and fiber modem cables, applying other WAN interface settings. Assuming it is not some other unexpected conflict in your setup, is it possible this is a regional issue? I am testing in the Chicago area.

Following is the content of my `/var/etc/dhcp6c_wan.conf`:
```
interface ngeth0 {
        send ia-na 0;   # request stateful address
        send ia-pd 0;   # request prefix delegation
        request domain-name-servers;
        request domain-name;
        script "/var/etc/dhcp6c_wan_dhcp6withoutra_script.sh"; # we'd like nameservers and RTSOLD to do all the work
};
id-assoc na 0 { };
id-assoc pd 0 {
        prefix ::/60 infinity;
        prefix-interface ix1.1 {
                sla-id 1;
                sla-len 4;
        };
        prefix-interface ix1.4 {
                sla-id 2;
                sla-len 4;
        };
        prefix-interface ix1.3 {
                sla-id 3;
                sla-len 4;
        };
        prefix-interface ix1.2 {
                sla-id 4;
                sla-len 4;
        };
        prefix-interface ix1.5 {
                sla-id 5;
                sla-len 4;
        };
        prefix-interface ix1.6 {
                sla-id 6;
                sla-len 4;
        };
};
```

**Comment by aus** [comment]
Even stranger, I tried your instructions again after a reboot and now it's working fine. I'd love to blame AT&T on this one, but I may have screwed something up. A reboot and a good night's sleep also seem to fix my other IPv6 issue of being pushed the wrong routes. I can even route to Cloudflare DNS `2606:4700:4700::1111` via my prefixed WAN of `2001:506:` (issue #11).

**Pull request merged**
